### ISSUE TITLE
Upgrade to cortex-m-rt 0.7.3

### ISSUE THREAD

**Issue by adamgreig** [imxrt-rs/imxrt-rt#7]
Hi all! We've recently fixed a bug in cortex-m-rt 0.7.1 and 0.7.2 which can lead to miscompilations under certain compiler optimisations, because the initial stack pointer is not 8-byte aligned. [Details here](https://github.com/rust-embedded/cortex-m/discussions/469).

The fix is in cortex-m-rt 0.7.3, which should hopefully be an easy upgrade, but as your `Cargo.toml` specifies `=0.7.2`, it won't be applied automatically.

**Comment by mciantyre** [comment]
Thanks for the fix and for the advisory. Yup, it's an easy upgrade. I'll have a 0.1.1 release out shortly.

Any new imxrt-rt user who fixes their dependency to 0.1.0 will observe a broken build. This is because cortex-m-rt 0.7.2 is yanked. I have no plan to also yank imxrt-rt 0.1.0, since I can rely on the upstream yank. If you're this imxrt-rt user, make sure you're using 0.1.1.
